Filipe.oliveira/con 1223
R3Conclave/conclave-core-sdk pull request #107
Opened 2022-11-28 10:38 UTC by filipesoliveira

2022-11-28 11:19 UTC, shamsasari commented
I'm not really in favour of exposing `enclave_worker_threads` to the user. It's really a short-term implementation detail of the Gramine process communication channel. See the TODO in `SocketEnclaveHostInterface`

2022-11-28 16:29 UTC, ac101m commented
> I'm not really in favour of exposing `enclave_worker_threads` to the user. It's really a short-term implementation detail of the Gramine process communication channel. See the TODO in `SocketEnclaveHostInterface`

Without a separate option, how will users be aware that some of their threads are being used internally by conclave?

2022-11-28 16:48 UTC, shamsasari commented
I don't see that as an issue, since we can explain that there is an overhead of threads which is used by Conclave, JVM, Gramine, etc. And since now we're setting this value to be quite high, the overhead should be proportionally small.

2022-11-28 17:00 UTC, ac101m commented
> I don't see that as an issue, since we can explain that there is an overhead of threads which is used by Conclave, JVM, Gramine, etc. And since now we're setting this value to be quite high, the overhead should be proportionally small.

So what should the call interface concurrency be set to? A constant value?

2022-11-28 17:31 UTC, shamsasari commented
I think so, for now at least. Going forward, we want to address that TODO, and create a new socket connection for each new thread, using ThreadLocals.

2022-11-28 17:35 UTC, ac101m reviewed
A trivial problem

2022-11-28 17:35 UTC, ac101m commented on docs/docs/enclave-configuration.md
> +    supportLanguages = ""
Got a bit of extraneous whitespace at the end of this line!

2022-11-28 18:01 UTC, shamsasari requested changes
Looking good. Two things:

1. Add an entry to api-changes.md, with a small explanation for why, and say that it doesn't affect enclave performance much.
2. The PR title is not reflective of the actual changes, it's just mirroring the original JIRA ticket.

2022-11-30 10:24 UTC, shamsasari commented on docs/docs/api-changes.md
> +considerable performance impact.
considerable -> major

2022-11-30 10:42 UTC, shamsasari approved these changes
Thanks

2022-11-30 12:28 UTC, merged

2022-11-30 12:40 UTC, filipesoliveira commented on plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/gramine/GenerateGramineDirectManifest.kt
> +            "-Denclave_worker_threads=10",
The default value was set to 10 so I decided to keep it. I don't know why we picked that value.