Gradle plugin cleanup
R3Conclave/conclave-core-sdk pull request #90
Opened 2022-11-07 14:24 UTC by shamsasari

Assorted cleanup of the plugin code:
* commandLine method takes in Strings rather than any object, to avoid accidently calling the wrong overload when using varargs vs Lists
* GraalVM tasks have been moved to a separate sub-package
* Better use of task dependencies to avoid need for dependsOn() calls
* Removed some dead code

2022-11-11 16:57 UTC, shamsasari commented
@bonifazi-r3 or @ac101m can you you please review. I've marked this as draft to make sure it doesn't land before #81 .

@bonifazi-r3 what's the status of the QA tests? Do you want me to wait until they are green until we merge this?

2022-11-14 15:35 UTC, bonifazi-r3 requested changes
First round, few questions

2022-11-14 15:35 UTC, bonifazi-r3 commented on plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/EnclaveBundleJar.kt
> +    val fileName: Property<String> = objects.property(String::class.java)
Isn't this an Output ? Just asking

2022-11-14 15:35 UTC, bonifazi-r3 commented on plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/EnclaveClassName.kt
> +    // result of the scan to a file which can then tracked by depdendent task. Notice how an @Output annotation
Typo, `depdendent`

2022-11-14 15:35 UTC, bonifazi-r3 commented on plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/EnclaveFatJar.kt
> +                copySpec.rename { PluginUtils.ENCLAVE_PROPERTIES }
Not an expert, but don't we miss an `Output` in this? I.e. my understanding is that when we create the task, at that moment we set the output (the name in this case).

2022-11-14 15:35 UTC, bonifazi-r3 commented on plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GenerateEnclaveMetadata.kt
> +                "-dumpfile", metadataFile.absolutePathString()
Mmm, trying to understand... Don't we miss an @Output in this as well anyway?

2022-11-14 15:35 UTC, bonifazi-r3 commented on plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GradleEnclavePlugin.kt
> +        val sourceFatJar: Provider<RegularFile> = if (pythonSourcePath == null) {
I know that sounds silly, but why don't start to we put code like this this in functions? It is polluting

2022-11-14 15:35 UTC, bonifazi-r3 commented on plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GradleEnclavePlugin.kt
> +        fun buildFile(path: String): Provider<RegularFile> = file("${type.name.lowercase()}/$path")
I don't understand this provider mechanism here. Why don't we just set the outputs with a File?

2022-11-15 12:59 UTC, ac101m reviewed
A few minor things

2022-11-15 12:59 UTC, ac101m commented on plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/GradleEnclavePlugin.kt
> +                null -> throw IllegalStateException()  // Keep the compiler happy
Do we need this? This `when()` statement seems to be exhaustive

2022-11-15 12:59 UTC, ac101m commented on plugin-enclave-gradle/src/main/kotlin/com/r3/conclave/plugin/enclave/gradle/SignEnclave.kt
>      val outputSignedEnclave: RegularFileProperty = objects.fileProperty()
Missed one!

(input/output in variable name)

2023-01-06 11:04 UTC, closed without merging